version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - ./gradlew clean packageLibs
      - ./gradlew packageSkinny
artifacts:
  files:
    - '*.zip'
  base-directory: 'build/distributions'
