version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - ./gradlew clean packageLibs
      - ./gradlew packageSkinny
  post_build:
    commands:
      - sam package --template-file template.yml --output-template-file package.yml --s3-bucket $S3BUCKET
artifacts:
  files:
    - '*.zip'
  base-directory: 'build/distributions'
